title: Aine Doyle's Technical Writing Portfolio
# author: Aine Doyle
# email: email@example.com
description: > # this means to ignore newlines until "show_excerpts:"
  Writing samples from my technical writing career at IBM.

show_excerpts: true # set to true to show excerpts on the homepage
permalink: /:categories/:year/:month/:day/:title:output_ext
baseurl: 
theme: pages-themes/jekyll-theme-cayman
plugins:
- jekyll-theme # add this line to the plugins list if you already have one
# Minima date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this

jekyll-theme-cayman:
  date_format: "%b %-d, %Y"

  # generate social links in footer
  social_links:
    # twitter: jekyllrb
    # github:  ainedoyle
    # rss: rss
    # dribbble: jekyll
    # facebook: jekyll
    # flickr:   jekyll
    # instagram:
    linkedin: aine-doyle-a3b752139
    # pinterest: jekyll
    # youtube: jekyll
    # youtube_channel: UC8CXR0-3I70i1tfPg1PAE1g
    # youtube_channel_name: CloudCannon
    # telegram: jekyll
    # googleplus: +jekyll
    # microdotblog: jekyll
    # keybase: jekyll

    # Mastodon instances
    # mastodon:
    # - username: jekyll
    #   instance: example.com
    # - username: jekyll2
    #   instance: example.com

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
header_pages:
-

# Build settings
theme: jekyll-theme-cayman

plugins:
 - jekyll-feed
 - jekyll-seo-tag

 # Google services
# google_analytics: UA-157005579-1